project:
  type: website

website:
  title: "Climate Crops"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - dataCollection.qmd
      - exploratoryAnalysis.qmd
      - model.qmd
format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: visual

